import { Geist, Geist_Mono, Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import NextProvider from "@/Provider/NextProvider";
import Footer from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const PoppinsFont = Poppins({
  variable: "--font-Poppins",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Productify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${PoppinsFont.variable} ${geistMono.variable} antialiased`}
      >

        <NextProvider>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer/>
        </NextProvider>
      </body>
    </html>
  );
}
